import type { HotelTask, HotelRoom, Message, ProblemReport, RoomHandover, ShiftLog, User } from "./types";
import { STAFF_IDS } from "./types";

export const DEMO_SEED_VERSION = "4";

export const DEMO_ACCOUNTS = {
  upravnik: {
    label: "Upravnik hotela",
    username: "upravnik",
    pin: "0000",
    role: "upravnik" as const,
    description: "Pregled celog hotela — prijave, obaveštenja, ljudi i sobe",
  },
  dezurni: {
    label: "Dežurna služba",
    username: "dezurni",
    pin: "1111",
    role: "dezurni" as const,
    description: "Inbox, prijave i poruke — odmah na početnoj",
  },
  stanar1: {
    label: "Marko Petrović",
    room: "205",
    pin: "1234",
    role: "stanar" as const,
    description: "Već ima prijave — pogledajte status ili pošaljite novu",
  },
  stanar2: {
    label: "Jelena Jovanović",
    room: "312",
    pin: "1234",
    role: "stanar" as const,
    description: "Soba 312 — ima 2 prijave",
  },
  stanar3: {
    label: "Nikola Nikolić",
    room: "108",
    pin: "1234",
    role: "stanar" as const,
    description: "Soba 108 — ima 1 prijavu u radu",
  },
  gost1: {
    label: "Ana Gost (privremeno)",
    room: "401",
    pin: "5678",
    role: "gost" as const,
    description: "Prijem sobe 401 i poruke dežurnoj službi",
  },
} as const;

export const DEMO_USERS: User[] = [
  {
    id: "demo-user-1",
    firstName: "Marko",
    lastName: "Petrović",
    fullName: "Marko Petrović",
    room: "205",
    pin: "1234",
    phone: "+381 64 111 0001",
    role: "stanar",
    createdAt: "2026-05-10T08:00:00.000Z",
    status: "active",
  },
  {
    id: "demo-user-2",
    firstName: "Jelena",
    lastName: "Jovanović",
    fullName: "Jelena Jovanović",
    room: "312",
    pin: "1234",
    phone: "+381 64 222 0002",
    role: "stanar",
    createdAt: "2026-05-15T10:30:00.000Z",
    status: "active",
  },
  {
    id: "demo-user-3",
    firstName: "Nikola",
    lastName: "Nikolić",
    fullName: "Nikola Nikolić",
    room: "108",
    pin: "1234",
    phone: "+381 64 333 0003",
    role: "stanar",
    createdAt: "2026-06-01T14:00:00.000Z",
    status: "active",
  },
  {
    id: "demo-user-gost1",
    firstName: "Ana",
    lastName: "Gost",
    fullName: "Ana Gost",
    room: "401",
    pin: "5678",
    phone: "+381 64 444 0004",
    role: "gost",
    createdAt: "2026-06-27T12:00:00.000Z",
    status: "active",
    createdById: STAFF_IDS.DEZURNI,
    createdByName: "Dežurna služba",
    boravakDo: "2026-07-05",
  },
];

const demoInv = (items: [string, number][]) =>
  items.map(([naziv, kolicina], i) => ({
    id: `demo-inv-${i}`,
    naziv,
    kolicina,
    stanje: "ispravno" as const,
  }));

export const DEMO_ROOMS: HotelRoom[] = [
  {
    id: "demo-room-205",
    broj: "205",
    sprat: "2",
    namena: "stanar",
    status: "zauzeta",
    stanje: "dobro",
    trebaRenoviranje: false,
    inventar: demoInv([
      ["Krevet jednokrevetni", 1],
      ["Orman", 1],
      ["Stoica", 1],
      ["TV", 1],
      ["Peškir", 2],
    ]),
    ocitanja: [
      {
        id: "demo-meter-1",
        tip: "struja",
        vrednost: "12450",
        jedinica: "kWh",
        datum: "2026-06-01",
      },
    ],
    dodeljeniUserId: "demo-user-1",
    createdAt: "2026-05-01T08:00:00.000Z",
    updatedAt: "2026-06-01T08:00:00.000Z",
  },
  {
    id: "demo-room-312",
    broj: "312",
    sprat: "3",
    namena: "stanar",
    status: "zauzeta",
    stanje: "odlicno",
    trebaRenoviranje: false,
    inventar: demoInv([
      ["Krevet dvokrevetni", 1],
      ["Orman", 1],
      ["Radni sto", 1],
      ["TV", 1],
    ]),
    ocitanja: [],
    dodeljeniUserId: "demo-user-2",
    createdAt: "2026-05-01T08:00:00.000Z",
    updatedAt: "2026-05-15T08:00:00.000Z",
  },
  {
    id: "demo-room-108",
    broj: "108",
    sprat: "1",
    namena: "stanar",
    status: "zauzeta",
    stanje: "zadovoljavajuce",
    trebaRenoviranje: true,
    napomenaRenoviranje: "Planirana zamena brava i farbanje zidova u Q3.",
    inventar: demoInv([
      ["Krevet jednokrevetni", 1],
      ["Orman", 1],
      ["TV", 1],
    ]),
    ocitanja: [],
    dodeljeniUserId: "demo-user-3",
    internaNapomena: "Brava na vratima — prioritet održavanja",
    createdAt: "2026-05-01T08:00:00.000Z",
    updatedAt: "2026-06-20T08:00:00.000Z",
  },
  {
    id: "demo-room-401",
    broj: "401",
    sprat: "4",
    namena: "gost",
    status: "slobodna",
    stanje: "dobro",
    trebaRenoviranje: false,
    inventar: demoInv([
      ["Krevet jednokrevetni", 1],
      ["Orman", 1],
      ["Stoica", 1],
      ["Peškir", 2],
      ["TV", 1],
    ]),
    ocitanja: [
      {
        id: "demo-meter-401",
        tip: "voda",
        vrednost: "842",
        jedinica: "m³",
        datum: "2026-06-27",
      },
    ],
    createdAt: "2026-06-01T08:00:00.000Z",
    updatedAt: "2026-06-27T08:00:00.000Z",
  },
];

export const DEMO_HANDOVERS: RoomHandover[] = [
  {
    id: "demo-handover-prijem-gost",
    roomId: "demo-room-401",
    brojSobe: "401",
    tip: "prijem",
    userId: "demo-user-gost1",
    userName: "Ana Gost",
    userRole: "gost",
    inventar: demoInv([
      ["Krevet jednokrevetni", 1],
      ["Orman", 1],
      ["Stoica", 1],
      ["Peškir", 2],
      ["TV", 1],
    ]),
    stanjeSobe: "dobro",
    korisnikPotvrdio: false,
    status: "ceka_korisnika",
    createdAt: "2026-06-27T12:05:00.000Z",
  },
  {
    id: "demo-handover-prijem-205",
    roomId: "demo-room-205",
    brojSobe: "205",
    tip: "prijem",
    userId: "demo-user-1",
    userName: "Marko Petrović",
    userRole: "stanar",
    inventar: demoInv([
      ["Krevet jednokrevetni", 1],
      ["Orman", 1],
      ["Stoica", 1],
      ["TV", 1],
      ["Peškir", 2],
    ]),
    stanjeSobe: "dobro",
    korisnikPotvrdio: true,
    korisnikPotvrdioAt: "2026-05-10T10:00:00.000Z",
    status: "zavrseno",
    dezurniPotvrda: {
      authorId: STAFF_IDS.DEZURNI,
      authorName: "Dežurna služba",
      stanje: "dobro",
      confirmedAt: "2026-05-10T11:00:00.000Z",
    },
    createdAt: "2026-05-10T09:00:00.000Z",
  },
];

export const DEMO_PROBLEMS: ProblemReport[] = [
  {
    id: "demo-problem-1",
    userId: "demo-user-1",
    fullName: "Marko Petrović",
    room: "205",
    category: "voda",
    description: "Slab pritisak vode u kupatilu, posebno ujutru. Problem traje treći dan.",
    phone: "+381 64 111 0001",
    status: "Primljeno",
    createdAt: "2026-06-26T09:15:00.000Z",
  },
  {
    id: "demo-problem-2",
    userId: "demo-user-1",
    fullName: "Marko Petrović",
    room: "205",
    category: "grejanje",
    description: "Radijator u dnevnoj sobi ne greje ravnomerno. Leva strana je hladna.",
    status: "U radu",
    createdAt: "2026-06-22T11:40:00.000Z",
    dezurniPotvrda: {
      preduzeteMere: true,
      napomena: "Serviser obavešten, intervencija zakazana.",
      confirmedAt: "2026-06-22T14:00:00.000Z",
      confirmedBy: "Dežurna služba",
    },
  },
  {
    id: "demo-problem-3",
    userId: "demo-user-1",
    fullName: "Marko Petrović",
    room: "205",
    category: "internet",
    description: "Wi-Fi signal u sobi je nestabilan, često prekida konekciju.",
    status: "Rešeno",
    createdAt: "2026-06-18T16:20:00.000Z",
    dezurniPotvrda: {
      preduzeteMere: true,
      confirmedAt: "2026-06-19T10:00:00.000Z",
      confirmedBy: "Dežurna služba",
    },
  },
  {
    id: "demo-problem-4",
    userId: "demo-user-2",
    fullName: "Jelena Jovanović",
    room: "312",
    category: "struja",
    description: "Utičnica pored kreveta ne radi. Provereno sa dva uređaja.",
    phone: "+381 64 222 0002",
    status: "Primljeno",
    createdAt: "2026-06-27T07:50:00.000Z",
  },
  {
    id: "demo-problem-5",
    userId: "demo-user-2",
    fullName: "Jelena Jovanović",
    room: "312",
    category: "higijena",
    description: "Potrebna je dodatna poseta sobe — zamena posteljine i osvežavanje.",
    status: "Rešeno",
    createdAt: "2026-06-20T13:00:00.000Z",
    dezurniPotvrda: {
      preduzeteMere: true,
      confirmedAt: "2026-06-20T16:00:00.000Z",
      confirmedBy: "Dežurna služba",
    },
  },
  {
    id: "demo-problem-6",
    userId: "demo-user-3",
    fullName: "Nikola Nikolić",
    room: "108",
    category: "drugo",
    description: "Brava na ulaznim vratima sobe se teško zaključava. Potrebna provera.",
    status: "U radu",
    createdAt: "2026-06-25T18:30:00.000Z",
  },
];

export const DEMO_TASKS: HotelTask[] = [
  {
    id: "demo-task-1",
    naslov: "Obilazak bloka B — provera ulaza",
    opis: "Proveriti stanje ulaza B i osigurati oznake za preusmeravanje stanara. Javiti upravniku po završetku.",
    prioritet: "hitno",
    status: "U radu",
    createdById: STAFF_IDS.UPRAVNIK,
    createdByName: "Upravnik hotela",
    createdAt: "2026-06-27T08:00:00.000Z",
    rok: "2026-06-27T18:00",
    zapazanja: [
      {
        id: "demo-obs-1",
        tekst: "Ulaz B zatvoren — postavljene trake i obaveštenje na ulazu A.",
        createdAt: "2026-06-27T09:30:00.000Z",
        authorName: "Dežurna služba",
      },
    ],
  },
  {
    id: "demo-task-2",
    naslov: "Evidencija prijava iz soba 201–210",
    opis: "Proveriti da li su stanari obavešteni o prekidu vodosnabdevanja. Uneti zapažanja u dnevnik smene.",
    prioritet: "obicno",
    status: "Dodeljen",
    createdById: STAFF_IDS.UPRAVNIK,
    createdByName: "Upravnik hotela",
    createdAt: "2026-06-27T07:00:00.000Z",
    zapazanja: [],
  },
];

export const DEMO_MESSAGES: Message[] = [
  {
    id: "demo-msg-1",
    fromUserId: STAFF_IDS.UPRAVNIK,
    fromRole: "upravnik",
    fromName: "Upravnik hotela",
    toUserId: "demo-user-1",
    toRole: "stanar",
    toName: "Marko Petrović",
    naslov: "Potvrda prijave — voda u sobi 205",
    tekst: "Primili smo vašu prijavu za pritisak vode. Održavanje je obavešteno i intervencija je zakazana za sutra ujutru.",
    createdAt: "2026-06-26T14:00:00.000Z",
    procitanoAt: "2026-06-26T15:00:00.000Z",
  },
  {
    id: "demo-msg-2",
    fromUserId: "demo-user-2",
    fromRole: "stanar",
    fromName: "Jelena Jovanović",
    fromRoom: "312",
    toUserId: STAFF_IDS.UPRAVNIK,
    toRole: "upravnik",
    toName: "Upravnik hotela",
    naslov: "Pitanje o smeštaju",
    tekst: "Molim informaciju da li je moguća promena sobe zbog buke iz susednog bloka.",
    createdAt: "2026-06-27T10:00:00.000Z",
  },
  {
    id: "demo-msg-3",
    fromUserId: "demo-user-3",
    fromRole: "stanar",
    fromName: "Nikola Nikolić",
    fromRoom: "108",
    toUserId: STAFF_IDS.DEZURNI,
    toRole: "dezurni",
    toName: "Dežurna služba",
    naslov: "Brava na vratima",
    tekst: "Brava se i dalje teško zaključava. Molim proveru večeras ako je moguće.",
    createdAt: "2026-06-27T11:30:00.000Z",
  },
];

export const DEMO_SHIFT_LOGS: ShiftLog[] = [
  {
    id: "demo-log-1",
    tip: "zapažanje",
    tekst: "U holu bloka A uočen povećan protok stanara zbog zatvorenog ulaza B. Redosled na ulazu A uredan.",
    createdAt: "2026-06-27T09:00:00.000Z",
    authorId: STAFF_IDS.DEZURNI,
    authorName: "Dežurna služba",
  },
  {
    id: "demo-log-2",
    tip: "primedba",
    tekst: "Stanar sobe 312 prijavio buku iz susednog bloka — proslediti upravniku za procenu smeštaja.",
    createdAt: "2026-06-27T10:15:00.000Z",
    authorId: STAFF_IDS.DEZURNI,
    authorName: "Dežurna služba",
  },
];
